language: bash

env:
  global:
    - DOCKER_CLI_EXPERIMENTAL=enabled
    - DOCKER_PLATFORMS=linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - travis_retry sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker run --privileged linuxkit/binfmt:v0.8  # Install qemu support
  - docker buildx create --name mybuild --use  # Enable multi-arch driver
  - docker login --username "$DOCKER_USERNAME" --password-stdin <<<"$DOCKER_PASSWORD"

deploy:
  - provider: script
    script: docker buildx build --platform="$DOCKER_PLATFORMS" --push -t "johnstarich/env2config:${TRAVIS_TAG}" .
    on:
      repo: JohnStarich/env2config
      tags: true
      condition: $TRAVIS_TAG =~ v[0-9]+\.[0-9]+\.[0-9]+
  - provider: script
    script: docker buildx build --platform="$DOCKER_PLATFORMS" --push -t "johnstarich/env2config:latest" .
    on:
      repo: JohnStarich/env2config
      branch: main
